---
title: "The Music of the Moral Emotions"
weight: 4
subtitle: "Analyzing moral content in messages, narratives, and other forms of public discourse."
description: |
  This is the resources page for a digital humanities course on corpus analytics for philosophers. Analyzing moral content in messages, narratives, and other forms of public discourse.
bibliography: "~/1-2021-22-Projects/references.bib"
cascade:
  draft: false
  # list or single layouts are possible
  layout: single-series # list, list-sidebar, single-series
  date: 2021-01-25
---

In fiction, as Jonathan Gilmore points out, some “facts may be described using different forms of figurative language and rhetoric, thereby eliciting different evaluations and emotional responses” [@gilm20, 113]. These are called *framing effects* and they occur when “the same content—e.g., a state of affairs, problem, or choice—is presented in different ways such that correspondingly different cognitive, explanatory, and evaluative attitudes toward that content are privileged” [@gilm20, 111]. This is done through *framing effects* which render alternative aspects of the content salient than what would occur in another context. For instance, to increase the fear one might feel, an artist can alter the lighting of a scene.

This is important because our emotions are evaluative appraisals of events and circumstances both in real life and in fictions.

This would suggest that there are norms for emotions. “. . . our emotional responses to the real world: we are frightened or delighted by real things, we like some real people and dislike others, we are made anxious by things that may turn out to be real and regret past failures . . .” [@curr20, 60].

and,

Such “emotions are often appropriate” it is “right to fear the fearful, to delight in the delightful, to feel secure with some people and wary of others, depending on how they are and what they do” [@curr20, 61].

Currie argues, and Gilmore agrees that Emotions contribute to our understanding of what occurs in a fiction. Emotions allow us to “get things right” in a fiction.

One method that artists have to tell a story then, is by prescribing certain emotions to their audience. Sometimes these prescriptions do not follow standard emotional norms. For instance, risky sex can be portrayed as appealing by highlighting the pleasure the participants experience and ignoring the potential consequences, say unintended pregnancy or heart break. 

Some media analysts see this as a point of concern: “Given the prevalence of infidelity among Americans, it is important to examine how infidelity is portrayed in media targeted to young adult listeners.” Specifically, this is interesting because “Both negative and positive consequences to infidelity were depicted [in their study of 1,500 popular music], and were most often accompanined by a nonchalant emotional tone” [@alex20a]. 

* emotions are evaluative representations in that they “instantiate[s] an appraisal of the *value* (to oneself or what one cares about) of that object” [@gilm20, 45; emphasis mine].

and

• Emotions instantiate the value we associate with the objects we encounter, whether in fiction or in real life.

Artists often use framing effects to communicate to their audiences. What these do is that they control the emotional experience the audience will have in regards to some occurence in  a fiction. If the audience experiences the correct emotion, the one prescribed by that artwork, then both the artist and audience are successful. If this does not occur, then either the audience or the artist has failed. This can be problematic in that sometimes the artist prescribes emotions to their audiences that would not be apt in real-world scenarios. For instance when the prescription relies on triggering “highly fallible in-group biases and implicit associations in shaping judgments about a character with sterotypical racial or ethnic characteristics” [@gilm20, 130]. 

This course attempts to look at different ways of answering the question: “how might we recognize the framing affects at work across a large corpus of documents and make an argument for the moral implications they suggest.”

This is a two semester course.


